import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';
import styled, { keyframes } from 'styled-components';

import { BleepsProvider } from '@arwes/sounds';
import { ArwesThemeProvider, StylesBaseline } from '@arwes/core';
import { useSetRecoilState } from 'recoil';
import { messageState } from '../atoms/messageState';
import { useState } from 'react';
const ROOT_FONT_FAMILY = '"Titillium Web", sans-serif';
const SOUND_OBJECT_URL = '/public/sounds/object.mp3';
const SOUND_TYPE_URL = '/public/sounds/type.mp3';
const audioSettings = { common: { volume: 0.25 } };
const playersSettings = {
  object: { src: [SOUND_OBJECT_URL] },
  type: { src: [SOUND_TYPE_URL], loop: true },
};
const bleepsSettings = {
  object: { player: 'object' },
  type: { player: 'type' },
};
const Rotation = keyframes`
  0%{ transform:rotate(0);}
  100%{ transform:rotate(360deg); }
`;
const BgWrapper = styled.div`
img{
  animation: ${Rotation} 60s linear infinite normal;,
}
`;
const imgSrc = '/images/animal_chara_computer_penguin.png';

const Home: NextPage = () => {
  const setMessage = useSetRecoilState(messageState);
  const [text, setText] = useState('');
  const router = useRouter();
  const handleClick = (e: any) => {
    e.preventDefault();
    setMessage('Hello, world!');
    router.push('/test');
  };

  const submitText = (e: any) => {
    e.preventDefault();
    setMessage(text);
    router.push('/test');
  };

  return (
    <ArwesThemeProvider>
      <BleepsProvider
        audioSettings={audioSettings}
        playersSettings={playersSettings}
        bleepsSettings={bleepsSettings}
      >
        <StylesBaseline styles={{ body: { fontFamily: ROOT_FONT_FAMILY } }} />
        <div className={styles.container}>
          <Head>
            <title>Create Next App</title>
            <meta name='description' content='Generated by create next app' />
            <link rel='icon' href='/favicon.ico' />
          </Head>

          <main className={styles.main}>
            <BgWrapper>
              <img
                src={imgSrc}
                className='fixed left-0 top-0 object-contain opacity-25 w-screen h-screen pointer-events-none'
              />
            </BgWrapper>
            <h1 className='text-red-300'>Welcome to IKE IKE Hello World!</h1>

            <div className='w-full md:w-96 md:max-w-full mx-auto'>
              <div className='p-6 border border-gray-300 sm:rounded-md'>
                <label className='mb-6 flex items-center '>
                  <span className='text-gray-200'>console.log(&quot;</span>
                  <input
                    onChange={(event) => {
                      setText(event.target.value);
                    }}
                    type='text'
                    name='name'
                    value={text}
                    className='block w-full mt-1 rounded-md shadow-sm focus:border-indigo-300  focus:ring-indigo-200 focus:ring-opacity-50'
                  />
                  <span className='text-gray-200'>&quot;)</span>
                </label>
                <div className='mb-6'>
                  <button
                    onClick={submitText}
                    type='submit'
                    className=' h-10 px-5 text-indigo-100 bg-indigo-700 rounded-lg transition-colors duration-150 focus:shadow-outline hover:bg-indigo-800'
                  >
                    Run
                  </button>
                </div>
                <div></div>
              </div>
            </div>
            <p className={styles.description}>↓忙しい人向け</p>
            <a href='' className={styles.card} onClick={handleClick}>
              <h2>Hello world! &rarr;</h2>
            </a>
          </main>

          <footer className={styles.footer}>
            <a
              href='https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app'
              target='_blank'
              rel='noopener noreferrer'
            >
              Powered by{' '}
              <span className={styles.logo}>
                <Image src='/vercel.svg' alt='Vercel Logo' width={72} height={16} />
              </span>
            </a>
          </footer>
        </div>
      </BleepsProvider>
    </ArwesThemeProvider>
  );
};

export default Home;
